### ISSUE TITLE
Question about different scores of the two different model

### ISSUE THREAD

**Issue by sky-fly97** [amirassov/kaggle-global-wheat-detection#1]
Hello, Why use this formula to change the scores of the two models? Can you tell me more about it.
 **scaled_scores = 0.5 * (rankdata(scores) / len(scores)) + 0.5.**

**Comment by amirassov** [comment]
Hi! This trick was used to fix the distribution shift between scores of two models. Because WBF is scale-sensitive. (https://arxiv.org/abs/1910.13302v1, 5.2). After applying this scaling we get scores with boundaries `[0.5, 1.0]`.Also I tried other scaling methods, but rankdata was better.
