### ISSUE TITLE
No module named 'mmdet.ops'

### ISSUE THREAD

**Issue by lyw615** [amirassov/kaggle-global-wheat-detection#4]
Thank you for your sharing. I am studying this  project . My local mmdetection is the newest version. And there is no ops module in  mmdetection and this project. It occurred with error
 `from mmdet.ops import ContextBlock, GeneralizedAttention
ModuleNotFoundError: No module named 'mmdet.ops` . Any resolution is appreciated

**Comment by lyw615** [comment]
The mmdetection version may be mmdetection-2.1.0

**Comment by wwpu** [comment]
Have you solved the issue?
